export default {
    products: [
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name:'Running Shorts',
            category: 'Shorts',
            image: '/images/product-2.jpg',
            price: 30,
            brand: 'Nike',
            rating: 4,
            numReviews: 11,
            countInStock: 3,
        },
        {
            _id:'3',
            name:'Running Shoes',
            category: 'Shoes',
            image: '/images/product-3.png',
            price: 129,
            brand: 'adidas',
            rating: 4.3,
            numReviews: 28,
            countInStock: 4,
        },
        {
            _id:'4',
            name:'Sports Cap',
            category: 'Apparel',
            image: '/images/product-4.png',
            price: 35,
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 66,
            countInStock: 20,
        },
        {
            _id:'5',
            name:'Canopy Jacket',
            category: 'Jackets',
            image: '/images/product-5.jpeg',
            price: 120,
            brand: 'Brooks',
            rating: 4.5,
            numReviews: 3,
            countInStock: 6,
        },
        {
            _id:'6',
            name:'Running Shoes',
            category: 'Shoes',
            image: '/images/product-6.jpeg',
            price: 150,
            brand: 'Hoka One',
            rating: 4,
            numReviews: 15,
            countInStock: 9,
        },
    ]
}