export default {
    products: [
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name:'Running Shorts',
            category: 'Shorts',
            image: '/images/product-2.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name:'Running Shoes',
            category: 'Shoes',
            image: '/images/product-3.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ]
}